pull_request_rules:
  - name: Merge dengan label
    conditions:
      - check-success=prettier
      - base=main
      - label=ready-to-merge
    actions:
      merge:
        method: squash
  - name: Conventional Commit
    conditions:
      - "title~=^(fix:|feat:|docs:|style:|refactor:|perf:|test:|build:|ci:|chore:|revert:)(?:\\(.+\\))?:"
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Title mengikuti conventional commit
          {% else %}
          Title tidak mengikuti conventional commit
          {% endif %}
        summary: |
          {% if not check_succeed %}
          Pull request title harus mengikuti [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/).
          {% endif %}
