pull_request_rules:
  - name: Merge dengan label
    conditions:
      - check-success=prettier
      - body~=(?m)^\[X\] [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/JavascriptAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua
      - base=main
      - label=ready-to-merge
    actions:
      merge:
        method: squash
