pull_request_rules:
  - name: ci testing kalo sukses ke squash dengan label
    conditions:
      - check-success=prettier
      - base=main
      - label=ready-to-merge
    actions:
      merge:
        method: squash
  - name: python label
    conditions:
      - files~=\.py$
    actions:
      label:
        add:
          - python files
  - name: markdown label
    conditions:
      - files~=\.md$
    actions:
      label:
        add:
          - markdown files
          
